# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build

on:
  pull_request:
    paths:
      - arm-templates
      - data
      - scripts
      - templates
      - widgets
  push:
    branches:
      - main
    paths:
      - arm-templates
      - data
      - scripts
      - templates
      - widgets
    
env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2 requests
    - name: Build
      run: python scripts/build.py
    - name: Commit changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Continuous Integration"
        output=$(git status -s)
        if [ ${#output} -gt 0 ]; then
          git add . && git commit -m "Added widgets" && git push
        fi
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        region: eastus2
        resourceGroupName: dashboards
        template: arm-templates/deployTemplate.json
        deploymentMode: Validate
        deploymentName: Dashboard
  
  Deploy:
    needs: Build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        region: eastus2
        resourceGroupName: dashboards
        template: arm-templates/deployTemplate.json
        deploymentMode: Validate
        deploymentName: Dashboard

