# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build Markdown widgets

on:
  push:
    paths: 
      - widgets/*
      - scripts/*
    branches-ignore: 
      - main

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2 requests
    - name: Build
      run: python scripts/build.py
    - name: Commit changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Continuous Integration"
        output=$(git status -s)
        if [ ${#output} -gt 0 ]; then
          git add . && git commit -m "Added widgets" && git push
        fi
