# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Deploy

on:
  workflow_dispatch:
env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

jobs:
  Deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Azure Login
      uses: Azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ env.AZURE_CREDENTIALS }}
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        region: eastus2
        resourceGroupName: dashboards
        template: arm-templates/deployTemplate.json
        deploymentMode: Incremental
        deploymentName: Dashboard
